### ISSUE TITLE
[BUG] InitialBridgeListener does not authorize when using Discord Activity URL Override

### ISSUE THREAD

**Issue by JadenH** [Furnyr/Dissonity#20]
**Describe the bug**
Authorization (fetching access token) is never done in the `rpc_bridge.js` when using a Discord Activity URL Override.

**Reproduction**
Steps to reproduce the behavior.
- Enable the activity URL override
- Launch the activity
- Observe via logs or breakpoints that the `COMMANDS.Authorize` in `InitialBridgeListener` is never invoked.

**Expected behavior**
`COMMANDS.Authorize` should be invoked in `InitialBridgeListener`.

**Platform**
If applicable, where were you executing the game? (Desktop/Mobile/Web)
Desktop / Discord PTB Client

**Additional context**
I verified that the `InitialBridgeListener` is added as a listener:
```js
function AddListeners(...args) {
    for (const listener of args) {
        window.addEventListener("message", listener);
        listeners.push(listener);
    }
}
```
It appears that the `message` here is never invoked. I've been unable to get to the root cause of where this event is emitted and why it is missing.

**Comment by JadenH** [comment]
I finally tracked it down right after posting the bug report. It looks like the `document.referrer` is set to `https://ptb.discord.com/` and it's throwing an exception:

```
Uncaught (in promise) RPCError: Invalid Origin
    at Y.a.tn.get.then.x.Z.closeCode (070d948dcb512896d44a.js:1:628542)
    at async E.handleHandshake (070d948dcb512896d44a.js:1:687078)
```

I tried removing the trailing slash, but I'm still getting the exception indicating that `https://ptb.discord.com` is not trusted.

---

Dove in even deeper into the electron app code and found this check:
```js
        function w(e) {
            let t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
            return t.indexOf(e) > -1
        }
```

`t` in this case is `https://<my-app-id>.discordsays.com/.proxy/staging` which is the staging URL I have given as my override URL.
`e` is `https://1293321286541381634.discordsays.com`.
Since t isn't found in e, it fails the check and throws the invalid origin exception:
```js
if (null == e || !w(n, [e]))
    throw new x.Z({
        closeCode: L.$VG.INVALID_ORIGIN
    },"Invalid Origin")
```

**Comment by JadenH** [comment]
I'm pretty confident this is an issue on Discord's end. It looks like someone else may also have run into this and posted on their Discord: https://ptb.discord.com/channels/613425648685547541/1300798040554344530/1300798040554344530

**Comment by Furnyr** [comment]
I agree that this looks like an issue with the Discord RPC. Even when using the official Embedded App SDK, I don't think I've ever been able to use the URL override.

Although it's true that I hadn't even considered overrides and most of the requests Dissonity made were against `https://<my-app-id>.discordsays.com/`, I wrote a fix (will commit it later) and the issue persisted.

**Comment by Furnyr** [comment]
Hi! It's been a while. After a few months, I decided to look into this again, now that Dissonity has moved from RpcBridge to hiRPC.

My results are the same, with `RPCError: Invalid Origin` being thrown by the Discord client when sending the RPC handshake. Unless this isn't the way URL overrides are supposed to be used, there's really nothing I can do on Dissonity's end.

Consider raising this issue to Discord directly. Feel free to open another issue or comment if you discover something new.

By the way, thank you for digging into this!
